services:
  nginx:
    image: "11notes/nginx:1.26.2"
    container_name: "nginx"
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "8443:8443/tcp"
    volumes:
      - "etc:/nginx/etc"
      - "var:/nginx/var"
      - "ssl:/nginx/ssl"
    restart: "always"
volumes:
  etc:
  var:
  ssl: