name: "nginx"
services:
  nginx:
    image: "11notes/nginx:1.26.3"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    ports:
      - "3000:3000/tcp"
    networks:
      frontend:
    volumes:
      - "etc:/nginx/etc"
      - "var:/nginx/var"
    tmpfs:
      - "/nginx/cache:uid=1000,gid=1000"
      - "/nginx/run:uid=1000,gid=1000"
    restart: "always"

volumes:
  etc:
  var:

networks:
  frontend: